// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATdJx46_3ZLkPsoohhlAbLGnBqT32RYcE',
    appId: '1:1015397055143:web:70bf6d7cf0497aecf23982',
    messagingSenderId: '1015397055143',
    projectId: 'flutter-firebase-8f220',
    authDomain: 'flutter-firebase-8f220.firebaseapp.com',
    storageBucket: 'flutter-firebase-8f220.firebasestorage.app',
    measurementId: 'G-QP93F9RT5D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAW5LY7NVOZWGZBVarNGfIT6fPv-04HIwY',
    appId: '1:1015397055143:android:e4a1bc8bf3d325a2f23982',
    messagingSenderId: '1015397055143',
    projectId: 'flutter-firebase-8f220',
    storageBucket: 'flutter-firebase-8f220.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMKiBATo-NBHemW4T7BdZefQj8AqK6oCI',
    appId: '1:1015397055143:ios:23629b57f8345a3ef23982',
    messagingSenderId: '1015397055143',
    projectId: 'flutter-firebase-8f220',
    storageBucket: 'flutter-firebase-8f220.firebasestorage.app',
    iosBundleId: 'com.example.myfirstapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMKiBATo-NBHemW4T7BdZefQj8AqK6oCI',
    appId: '1:1015397055143:ios:23629b57f8345a3ef23982',
    messagingSenderId: '1015397055143',
    projectId: 'flutter-firebase-8f220',
    storageBucket: 'flutter-firebase-8f220.firebasestorage.app',
    iosBundleId: 'com.example.myfirstapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATdJx46_3ZLkPsoohhlAbLGnBqT32RYcE',
    appId: '1:1015397055143:web:075b972bd94f1e7ef23982',
    messagingSenderId: '1015397055143',
    projectId: 'flutter-firebase-8f220',
    authDomain: 'flutter-firebase-8f220.firebaseapp.com',
    storageBucket: 'flutter-firebase-8f220.firebasestorage.app',
    measurementId: 'G-1Z7KKZQ6XG',
  );
}
